name: Build Test Lint
on: [pull_request]
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
#      - name: Build the app
#        run: ./gradlew build
#      - name: Run unit tests
#        run: ./gradlew testDevDebug --stacktrace
#      - name: Run Kotlin Linter
#        run: ./gradlew ktlintCheck
#      - name: Run detekt
#        run: ./gradlew detekt